server:
  port: 8200
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8122
          predicates:
            - Path=/api/user/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qosEnable: true
    qosPort: 3333
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: 31111
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
